name: Deploy project to Github Pages with Vite

on:
  # 기본 브랜치에 대한 푸시 이벤트 발생 시 실행
  push:
    branches: ["main"]

  # Actions 탭에서 수동으로 워크플로우를 실행할 수 있도록 구성
  workflow_dispatch:

# 동시에 하나의 배포만 허용하도록 구성
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 단순히 배포만 수행하기에 하나의 잡으로만 구성
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Access to Secrets
        run: |
          echo "API_KEY=VITE_API_KEY" >> .env
          echo "AUTH_DOMAIN=VITE_AUTH_DOMAIN" >> .env
          echo "PROJECT_ID=VITE_PROJECT_ID" >> .env
          echo "STORAGE_BUCKET=VITE_STORAGE_BUCKET" >> .env
          echo "MESSAGING_SENDER_ID=VITE_MESSAGING_SENDER_ID" >> .env
          echo "APP_ID=VITE_APP_ID" >> .env
        env: |
          API_KEY: ${{secrets.VITE_API_KEY}}
          AUTH_DOMAIN: ${{secrets.VITE_AUTH_DOMAIN}}
          PROJECT_ID: ${{secrets.VITE_PROJECT_ID}}
          STORAGE_BUCKET: ${{secrets.VITE_STORAGE_BUCKET}}
          MESSAGING_SENDER_ID: ${{secrets.VITE_MESSAGING_SENDER_ID}}
          APP_ID: ${{secrets.VITE_APP_ID}}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # dist 디렉터리 업로드
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
